version: '3.8'

services:
  oficinamotorcycle.api:
    image: ${DOCKER_REGISTRY-}oficinamotorcycleapi
    build:
      context: .
      dockerfile: OficinaMotorcycle.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=oficinadb;Username=postgres;Password=teste123
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: oficinadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynetwork

      
volumes:
  postgres_data:

networks:
  mynetwork:
